# Generated by Django 6.0.5 on 2026-05-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('TRUCK', 'Camión'), ('VAN', 'Furgoneta'), ('MOTORCYCLE', 'Motocicleta'), ('OTHER', 'Otro')], max_length=15)),
                ('capacity_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacity_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'transport_transport',
            },
        ),
    ]
